name: Run Automation Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # Runs at 1:00 PM UTC daily

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest or any other dependencies
        pip install playwright  # Install playwright
        python -m playwright install  # Install necessary browsers for playwright

    - name: Run tests with pytest
      run: |
        python logtest.py 
        python pages/test_loginPage_F.py  # Corrected the path separator
        python pages/test_signupPage_F.py  # Corrected the path separator
        python pages/test_request_quote_flow.py  # Corrected the path separator
        pytest --html=report.html --self-contained-html  # Run all tests and generate report
